### ISSUE TITLE
Can you make it compatible with API 3.x.x?

### ISSUE THREAD

**Issue by GooglePlugin** [legoboy0215/Turrets#3]
Please make it available if you are available. I can't wait to try this fantastic plugin! Thank you!

**Comment by legoboy0215** [comment]
I'll try.

**Comment by GooglePlugin** [comment]
Thanks! I can help you test it if you want.

**Comment by legoboy0215** [comment]
Can you try the 3.x branch?

**Comment by GooglePlugin** [comment]
OK, I will.

**Comment by GooglePlugin** [comment]
Congratulations!! It works!!! Thank you!
